import course1 from "@/assets/course-1.png";
import course2 from "@/assets/course-2.png";
import course3 from "@/assets/course-3.png";
import course4 from "@/assets/course-4.png";
import course5 from "@/assets/course-5.png";
import course6 from "@/assets/course-6.png";

export const baseCourses = [
  {
    image: course1,
    title: "Learn Figma from Basic",
    author: "purpearl studio",
    rating: "4.5",
    level: "Beginner",
    price: "$25",
    tag: "lifetime",
    duration: "2 hours 16 mins",
    lessons: "17 Lessons",
    comments: "69 Comments",
    avatars: [1, 2, 3],
    extra: "20+",
  },
  {
    image: course2,
    title: "Build Digital Asset",
    author: "purpearl studio",
    rating: "4.5",
    level: "Beginner",
    price: "$25",
    tag: "lifetime",
    duration: "2 hours 16 mins",
    lessons: "17 Lessons",
    comments: "69 Comments",
    avatars: [4, 5, 6],
    extra: "20+",
  },
  {
    image: course3,
    title: "the Power of Big Data",
    author: "purpearl studio",
    rating: "4.5",
    level: "Beginner",
    price: "$25",
    tag: "lifetime",
    duration: "2 hours 16 mins",
    lessons: "17 Lessons",
    comments: "69 Comments",
    avatars: [7, 8, 9],
    extra: "20+",
  },
  {
    image: course4,
    title: "Balancing Productivity an...",
    author: "purpearl studio",
    rating: "4.5",
    level: "Beginner",
    price: "$25",
    tag: "lifetime",
    duration: "2 hours 16 mins",
    lessons: "17 Lessons",
    comments: "69 Comments",
    avatars: [10, 11, 12],
    extra: "20+",
  },
  {
    image: course5,
    title: "Mastering Money Manage...",
    author: "purpearl studio",
    rating: "4.5",
    level: "Beginner",
    price: "$25",
    tag: "lifetime",
    duration: "2 hours 16 mins",
    lessons: "17 Lessons",
    comments: "69 Comments",
    avatars: [13, 14, 15],
    extra: "20+",
  },
  {
    image: course6,
    title: "From Idea to Startup Succ...",
    author: "purpearl studio",
    rating: "4.5",
    level: "Beginner",
    price: "$25",
    tag: "lifetime",
    duration: "2 hours 16 mins",
    lessons: "17 Lessons",
    comments: "69 Comments",
    avatars: [16, 17, 18],
    extra: "20+",
  },
];
